site_name: Emmanuel Sleiman
site_url: https://github.com/haematool/haematool
theme:
  name: material
  language : en
  icon:
    logo: material/library
  
  palette: 
    scheme: slate
    primary : blue grey
    accent : amber

  

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.share
  
plugins:
    - search
    - tags
    - blog

nav:
  - Home: index.md
  - About me: about.md
  - R Studio Server: rstudioserver/rstudio.md
  - Machine Learning: machinelearning/mrdpraidict.md
  - Deep Learning: deeplearning/sicklecellvision.md
  - Blog:
    - blog/index.md
repo_url: https://github.com/haematool/haematool
repo_name: Haematool
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://fr.linkedin.com/in/emmanuel-sleiman-0354272b4
copyright : Emmanuel Sleiman - 2024 Copyright